"""empty message

Revision ID: 013d3b636a0b
Revises: a49f8ef9af3a
Create Date: 2022-07-23 23:55:29.605032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '013d3b636a0b'
down_revision = 'a49f8ef9af3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'inbox', 'unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'unit_id')
    # ### end Alembic commands ###
