"""empty message

Revision ID: 035289a9fb4c
Revises: 0d92c0f43ce7
Create Date: 2022-07-23 23:49:10.519528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '035289a9fb4c'
down_revision = '0d92c0f43ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('service_area_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'patient', 'service_area', ['service_area_id'], ['id'])
    op.add_column('service_area', sa.Column('name', sa.String(), nullable=False))
    op.add_column('service_area', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_area', 'description')
    op.drop_column('service_area', 'name')
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'service_area_id')
    # ### end Alembic commands ###
