"""empty message

Revision ID: 0d92c0f43ce7
Revises: 8f1491c8dfa4
Create Date: 2022-07-23 23:48:46.700762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d92c0f43ce7'
down_revision = '8f1491c8dfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'patient', 'unit', ['unit_id'], ['id'])
    op.add_column('unit', sa.Column('name', sa.String(), nullable=False))
    op.add_column('unit', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'description')
    op.drop_column('unit', 'name')
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'unit_id')
    # ### end Alembic commands ###
