"""empty message

Revision ID: 1df80d32b3a1
Revises: 9c0fea623cb5
Create Date: 2022-07-24 17:15:57.211461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df80d32b3a1'
down_revision = '9c0fea623cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_phone_number_key', 'patient', type_='unique')
    op.drop_constraint('provider_phone_number_key', 'provider', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('provider_phone_number_key', 'provider', ['phone_number'])
    op.create_unique_constraint('patient_phone_number_key', 'patient', ['phone_number'])
    # ### end Alembic commands ###
