"""empty message

Revision ID: 6beb2581ad40
Revises: aecf55e036cc
Create Date: 2022-07-23 23:46:58.161452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6beb2581ad40'
down_revision = 'aecf55e036cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('patient_recipient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('inbox', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('inbox', sa.Column('message', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'inbox', 'patient', ['patient_recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'message')
    op.drop_column('inbox', 'title')
    op.drop_column('inbox', 'patient_recipient_id')
    # ### end Alembic commands ###
