"""empty message

Revision ID: 792806210a01
Revises: d385ea04c60e
Create Date: 2022-07-23 23:52:58.045696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '792806210a01'
down_revision = 'd385ea04c60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.String(), nullable=False))
    op.add_column('department', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('provider', sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'provider', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'department_id')
    op.drop_column('department', 'description')
    op.drop_column('department', 'name')
    # ### end Alembic commands ###
