"""empty message

Revision ID: 9c0fea623cb5
Revises: 9e7883b6e612
Create Date: 2022-07-24 07:51:45.474850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0fea623cb5'
down_revision = '9e7883b6e612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('state', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'state')
    # ### end Alembic commands ###
