"""empty message

Revision ID: 9e7883b6e612
Revises: 19ef9cec2f1b
Create Date: 2022-07-23 23:56:39.863790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e7883b6e612'
down_revision = '19ef9cec2f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('service_area_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'inbox', 'service_area', ['service_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'service_area_id')
    # ### end Alembic commands ###
