"""empty message

Revision ID: a49f8ef9af3a
Revises: 79ed5cbaf618
Create Date: 2022-07-23 23:54:52.257080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a49f8ef9af3a'
down_revision = '79ed5cbaf618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'inbox', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'department_id')
    # ### end Alembic commands ###
