"""empty message

Revision ID: a5ce826a63dc
Revises: d470ba038fe2
Create Date: 2022-07-23 23:50:19.365287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5ce826a63dc'
down_revision = 'd470ba038fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostic', sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('diagnostic', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('diagnostic', sa.Column('medications', sa.String(), nullable=False))
    op.create_foreign_key(None, 'diagnostic', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnostic', type_='foreignkey')
    op.drop_column('diagnostic', 'medications')
    op.drop_column('diagnostic', 'summary')
    op.drop_column('diagnostic', 'patient_id')
    # ### end Alembic commands ###
