"""empty message

Revision ID: aecf55e036cc
Revises: 024cf3d27482
Create Date: 2022-07-23 23:46:07.622816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aecf55e036cc'
down_revision = '024cf3d27482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('consultant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('patient', sa.Column('patient_hospital_id', sa.String(length=30), nullable=False))
    op.add_column('patient', sa.Column('religion', sa.String(length=60), nullable=False))
    op.add_column('patient', sa.Column('occupation', sa.String(length=255), nullable=False))
    op.add_column('patient', sa.Column('relationship_status', sa.String(length=100), nullable=False))
    op.add_column('patient', sa.Column('next_of_kin_name', sa.String(length=255), nullable=False))
    op.add_column('patient', sa.Column('next_of_kin_address', sa.String(length=255), nullable=False))
    op.add_column('patient', sa.Column('next_of_kin_phone', sa.Integer(), nullable=False))
    op.add_column('patient', sa.Column('next_of_kin_gender', sa.String(length=30), nullable=False))
    op.add_column('patient', sa.Column('next_of_kin_relationship', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_patient_patient_hospital_id'), 'patient', ['patient_hospital_id'], unique=True)
    op.create_foreign_key(None, 'patient', 'provider', ['consultant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_index(op.f('ix_patient_patient_hospital_id'), table_name='patient')
    op.drop_column('patient', 'next_of_kin_relationship')
    op.drop_column('patient', 'next_of_kin_gender')
    op.drop_column('patient', 'next_of_kin_phone')
    op.drop_column('patient', 'next_of_kin_address')
    op.drop_column('patient', 'next_of_kin_name')
    op.drop_column('patient', 'relationship_status')
    op.drop_column('patient', 'occupation')
    op.drop_column('patient', 'religion')
    op.drop_column('patient', 'patient_hospital_id')
    op.drop_column('patient', 'consultant_id')
    # ### end Alembic commands ###
