"""empty message

Revision ID: b6072c4383fa
Revises: 792806210a01
Create Date: 2022-07-23 23:53:17.781601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6072c4383fa'
down_revision = '792806210a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'provider', 'unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'unit_id')
    # ### end Alembic commands ###
