"""empty message

Revision ID: cc1f90f452f4
Revises: b6072c4383fa
Create Date: 2022-07-23 23:53:35.689673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc1f90f452f4'
down_revision = 'b6072c4383fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('service_area_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'provider', 'service_area', ['service_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'service_area_id')
    # ### end Alembic commands ###
