"""empty message

Revision ID: cd7629f70869
Revises: 80d88346e202
Create Date: 2022-07-23 23:52:08.728947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd7629f70869'
down_revision = '80d88346e202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('provider_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'address', 'provider', ['provider_id'], ['id'])
    op.add_column('provider', sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('provider', sa.Column('staff_id', sa.String(length=30), nullable=False))
    op.add_column('provider', sa.Column('is_consultant', sa.Boolean(), nullable=False))
    op.add_column('provider', sa.Column('specialty', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_provider_staff_id'), 'provider', ['staff_id'], unique=True)
    op.create_foreign_key(None, 'provider', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_index(op.f('ix_provider_staff_id'), table_name='provider')
    op.drop_column('provider', 'specialty')
    op.drop_column('provider', 'is_consultant')
    op.drop_column('provider', 'staff_id')
    op.drop_column('provider', 'address_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'provider_id')
    # ### end Alembic commands ###
