"""empty message

Revision ID: d385ea04c60e
Revises: cd7629f70869
Create Date: 2022-07-23 23:52:37.508281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd385ea04c60e'
down_revision = 'cd7629f70869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('provider_recipient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'inbox', 'provider', ['provider_recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'provider_recipient_id')
    # ### end Alembic commands ###
